<?php
/** 
 * Liang Lee Hide Top Bar
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2013.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File start.php
 */
elgg_register_event_handler('init', 'system', 'hidetopbar_init'); 

function hidetopbar_init() {

elgg_extend_view('page/elements/head', 'hidetopbar/hide', 9999999);

}

