<?php
/** 
 * Liang Lee Hide Top Bar
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2013.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File version.php
 */
$LiangLee_version = '10012013';
$LiangLee_release = '1.0'; 
