<?php
/** 
 * Liang Lee Hide Top Bar
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2013.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File version.php
 */
?>
<style>.elgg-page-topbar {display: none;}</style>
